<?php

namespace Database\Seeders;

use App\Models\Book;
use Carbon\Carbon;
use Illuminate\Container\Attributes\Log;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log as FacadesLog;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'title' => 'The Silent Patient',
                'isbn' => '9781250301697',
                'description' => 'A 2019 psychological thriller. Celadon Books.',
                'publication_date' => '2019-02-05',
                'pages' => 384,
                'language' => 'English',
                'publisher' => 'Celadon Books',
                'cover_image' => 'seed/the-silent-patient.jpeg',
                'rental_price_per_week' => 300,  // NPR
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Thriller', 'Fiction'],
            ],
            [
                'title' => 'Shirishko Phool',
                'isbn' => '9789937827003',
                'description' => 'Parijat’s first and award‑winning novel (1964).',
                'publication_date' => '1964-01-01',
                'pages' => 220,
                'language' => 'Nepali',
                'publisher' => 'Jagadamba Press',
                'cover_image' => 'seed/shirish-ko-phool.jpg',
                'rental_price_per_week' => 150,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Classic', 'Fiction'],
            ],
            [
                'title' => 'Muna Madan',
                'isbn' => '9789993326908',
                'description' => 'Buddhisagar’s bestselling bildungsroman, 2010. A young boy’s life story.',
                'publication_date' => '2010-01-01',
                'pages' => 400,
                'language' => 'Nepali',
                'publisher' => 'FinePrint Publication',
                'cover_image' => 'seed/karnali-blues.jpg',
                'rental_price_per_week' => 180,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Romance', 'Historical'],
            ],
            [
                'title' => 'Seto Dharti',
                'isbn' => '9789937856348',
                'description' => 'Madan Puraskar–winning novel (2012) about a hill‑girl’s journey.',
                'publication_date' => '2012-03-01',
                'pages' => 373,
                'language' => 'Nepali',
                'publisher' => 'Fineprints Books',
                'cover_image' => 'seed/seto-dharti.jpg',
                'rental_price_per_week' => 170,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Historical', 'Fiction'],
            ],
            [
                'title' => 'Phirphire',
                'isbn' => '9789937665018',
                'description' => '2016 novel sequeling Karnali Blues, nominated for Madan Puraskar.',
                'publication_date' => '2016-01-23',
                'pages' => 544,
                'language' => 'Nepali',
                'publisher' => 'FinePrint Publications',
                'cover_image' => 'seed/phirphire.jpg',
                'rental_price_per_week' => 200,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Fiction'],
            ],
            [
                'title' => 'Dumero',
                'isbn' => '9789937937801',
                'description' => 'Debut contemporary novel (2020).',
                'publication_date' => '2020-07-31',
                'pages' => 328,
                'language' => 'Nepali',
                'publisher' => 'Nepalaya Publication',
                'cover_image' => 'seed/Dumero.jpg',
                'rental_price_per_week' => 160,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Romance', 'Fiction'],
            ],
            [
                'title' => 'Saaya',
                'isbn' => '9789937887779',
                'description' => 'Romantic sequel to Summer Love (2014).',
                'publication_date' => '2014-08-01',
                'pages' => 242,
                'language' => 'Nepali',
                'publisher' => 'Fine Print',
                'cover_image' => 'seed/saaya.jpg',
                'rental_price_per_week' => 140,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Romance'],
            ],
            [
                'title' => 'Sumnima',
                'isbn' => '9788173030482',
                'description' => 'Psychological love story set in 1964, written by Nepal’s first PM.',
                'publication_date' => '1969-01-01',
                'pages' => 94,
                'language' => 'Nepali',
                'publisher' => 'Sajha Prakashan',
                'cover_image' => 'seed/sumnima.jpg',
                'rental_price_per_week' => 120,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Classic', 'Romance'],
            ],
            [
                'title' => 'Godaan',
                'isbn' => '9788172233822',
                'description' => 'A classic social novel by Premchand about village life.',
                'publication_date' => '1936-01-01',
                'pages' => 336,
                'language' => 'Hindi',
                'publisher' => 'Motilal Banarsidass',
                'cover_image' => 'seed/godaan.png',
                'rental_price_per_week' => 150,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Classic', 'Fiction'],
            ],
            [
                'title' => 'Rag Darbari',
                'isbn' => '9788184751445',
                'description' => 'Satirical novel of rural India.',
                'publication_date' => '1968-01-01',
                'pages' => 266,
                'language' => 'Hindi',
                'publisher' => 'Penguin India',
                'cover_image' => 'seed/rag-darbari.jpg',
                'rental_price_per_week' => 160,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Satire', 'Fiction'],
            ],
            [
                'title' => 'Madhushala',
                'isbn' => '9788190483735',
                'description' => 'Legendary Hindi poetry collection.',
                'publication_date' => '1935-01-01',
                'pages' => 197,
                'language' => 'Hindi',
                'publisher' => 'Rajkamal Prakashan',
                'cover_image' => 'seed/madhushala.jpg',
                'rental_price_per_week' => 130,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Poetry', 'Fiction'],
            ],
            [
                'title' => 'Suraj ka Satvan Ghoda',
                'isbn' => '9788170460516',
                'description' => 'Experimental novel of yarns within tales.',
                'publication_date' => '1968-01-01',
                'pages' => 248,
                'language' => 'Hindi',
                'publisher' => 'Arnold-Heinemann',
                'cover_image' => 'seed/suraj-ka-satva-ghoda.jpg',
                'rental_price_per_week' => 140,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Fiction'],
            ],
            [
                'title' => 'Karnali Blues (English translated)',
                'isbn' => '9780670096602',
                'description' => 'English translation of the Nepali bestseller (2022).',
                'publication_date' => '2022-05-01',
                'pages' => 432,
                'language' => 'English',
                'publisher' => 'Penguin Classics',
                'cover_image' => 'seed/karnali-blues-en.jpeg',
                'rental_price_per_week' => 250,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Historical']
            ],
            [
                'title' => 'One Hundred Years of Solitude',
                'isbn' => '9780060883287',
                'description' => 'Spanish‑language masterpiece of magical realism (1967).',
                'publication_date' => '1967-06-05',
                'pages' => 417,
                'language' => 'Spanish',
                'publisher' => 'Harper & Row',
                'cover_image' => 'seed/one-hundred-years.jpg',
                'rental_price_per_week' => 280,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Magical Realism', 'Classic']
            ],
            [
                'title' => 'Atomic Habits',
                'isbn' => '9780735211292',
                'description' => 'A proven framework for building good habits and breaking bad ones.',
                'publication_date' => '2018-10-16',
                'pages' => 320,
                'language' => 'English',
                'publisher' => 'Avery',
                'cover_image' => 'seed/atomic-habits.webp',
                'rental_price_per_week' => 200,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Self-help', 'Productivity']
            ],
            [
                'title' => 'The Alchemist',
                'isbn' => '9780061122415',
                'description' => 'A fable about following your dreams, originally published in Portuguese.',
                'publication_date' => '1988-04-15',
                'pages' => 208,
                'language' => 'English',
                'publisher' => 'HarperOne',
                'cover_image' => 'seed/the-alchemist.webp',
                'rental_price_per_week' => 180,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Fiction', 'Philosophy']
            ],
            [
                'title' => 'Palpasa Cafe',
                'isbn' => '9789937905879',
                'description' => 'A novel set during the Nepalese civil war, blending art and conflict.',
                'publication_date' => '2005-05-01',
                'pages' => 232,
                'language' => 'Nepali',
                'publisher' => 'Nepalaya Publication',
                'cover_image' => 'seed/palpasa-cafe.jpg',
                'rental_price_per_week' => 170,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Fiction', 'Political']
            ],
            [
                'title' => 'The Kite Runner',
                'isbn' => '9781594631931',
                'description' => 'Heartbreaking tale of friendship and redemption set in Afghanistan.',
                'publication_date' => '2003-05-29',
                'pages' => 372,
                'language' => 'English',
                'publisher' => 'Riverhead Books',
                'cover_image' => 'seed/the-kite-runner.webp',
                'rental_price_per_week' => 200,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Historical', 'Fiction']
            ],
            [
                'title' => 'The Subtle Art of Not Giving a F*ck',
                'isbn' => '9780062457714',
                'description' => 'A counterintuitive approach to living a good life.',
                'publication_date' => '2016-09-13',
                'pages' => 224,
                'language' => 'English',
                'publisher' => 'Harper',
                'cover_image' => 'seed/subtle-art.jpg',
                'rental_price_per_week' => 190,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Self-help', 'Philosophy']
            ],
            [
                'title' => 'Rich Dad Poor Dad',
                'isbn' => '9781612680194',
                'description' => 'Personal finance classic that contrasts two financial mindsets.',
                'publication_date' => '1997-04-01',
                'pages' => 336,
                'language' => 'English',
                'publisher' => 'Plata Publishing',
                'cover_image' => 'seed/rich-dad.jpg',
                'rental_price_per_week' => 160,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Finance', 'Self-help']
            ],
            [
                'title' => 'Half Girlfriend',
                'isbn' => '9788129135721',
                'description' => 'A romantic drama between a small-town boy and a high-society girl.',
                'publication_date' => '2014-10-01',
                'pages' => 260,
                'language' => 'English',
                'publisher' => 'Rupa Publications',
                'cover_image' => 'seed/half-girlfriend.jpg',
                'rental_price_per_week' => 150,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Romance', 'Fiction']
            ],
            [
                'title' => 'The Book Thief',
                'isbn' => '9780375842207',
                'description' => 'A story narrated by Death during Nazi Germany.',
                'publication_date' => '2005-03-14',
                'pages' => 552,
                'language' => 'English',
                'publisher' => 'Knopf Books for Young Readers',
                'cover_image' => 'seed/book-thief.jpg',
                'rental_price_per_week' => 220,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Historical', 'Fiction']
            ],
            [
                'title' => 'Think and Grow Rich',
                'isbn' => '9781585424337',
                'description' => 'Timeless principles on wealth and mindset.',
                'publication_date' => '1937-01-01',
                'pages' => 238,
                'language' => 'English',
                'publisher' => 'TarcherPerigee',
                'cover_image' => 'seed/think-grow-rich.jpg',
                'rental_price_per_week' => 140,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Motivational', 'Self-help']
            ],
            [
                'title' => 'Harry Potter and the Sorcerer\'s Stone',
                'isbn' => '9780590353427',
                'description' => 'The first book in the globally acclaimed fantasy series.',
                'publication_date' => '1997-06-26',
                'pages' => 309,
                'language' => 'English',
                'publisher' => 'Scholastic',
                'cover_image' => 'seed/harry-potter-1.jpg',
                'rental_price_per_week' => 210,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Fantasy', 'Adventure']
            ],
            [
                'title' => 'To Kill a Mockingbird',
                'isbn' => '9780061120084',
                'description' => 'A gripping tale of racial injustice and childhood innocence in the American South.',
                'publication_date' => '1960-07-11',
                'pages' => 376,
                'language' => 'English',
                'publisher' => 'Harper Perennial',
                'cover_image' => 'seed/to-kill-mockingbird.jpg',
                'rental_price_per_week' => 250,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Classic', 'Fiction'],
            ],
            [
                'title' => '1984',
                'isbn' => '9780451524935',
                'description' => 'Dystopian masterpiece about totalitarian surveillance and control.',
                'publication_date' => '1949-06-08',
                'pages' => 328,
                'language' => 'English',
                'publisher' => 'Signet Classic',
                'cover_image' => 'seed/1984.jpg',
                'rental_price_per_week' => 280,
                'total_copies' => 5,
                'available_copies' => 5,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Dystopian', 'Classic'],
            ],
            [
                'title' => 'Pride and Prejudice',
                'isbn' => '9780141439518',
                'description' => 'Timeless romance exploring love, class, and social expectations.',
                'publication_date' => '1813-01-28',
                'pages' => 432,
                'language' => 'English',
                'publisher' => 'Penguin Classics',
                'cover_image' => 'seed/pride-prejudice.jpg',
                'rental_price_per_week' => 220,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Romance', 'Classic'],
            ],
            [
                'title' => 'The Great Gatsby',
                'isbn' => '9780743273565',
                'description' => 'The American Dream\'s dark side in the Jazz Age.',
                'publication_date' => '1925-04-10',
                'pages' => 180,
                'language' => 'English',
                'publisher' => 'Scribner',
                'cover_image' => 'seed/great-gatsby.jpg',
                'rental_price_per_week' => 240,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Classic', 'Fiction'],
            ],
            [
                'title' => 'Lord of the Flies',
                'isbn' => '9780571056866',
                'description' => 'A haunting tale of civilization\'s fragility among stranded schoolboys.',
                'publication_date' => '1954-09-17',
                'pages' => 224,
                'language' => 'English',
                'publisher' => 'Faber & Faber',
                'cover_image' => 'seed/lord-flies.jpg',
                'rental_price_per_week' => 200,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Classic', 'Fiction'],
            ],
            [
                'title' => 'The Catcher in the Rye',
                'isbn' => '9780316769174',
                'description' => 'Holden Caulfield\'s journey through adolescent alienation.',
                'publication_date' => '1951-07-16',
                'pages' => 277,
                'language' => 'English',
                'publisher' => 'Little, Brown and Company',
                'cover_image' => 'seed/catcher-rye.jpg',
                'rental_price_per_week' => 230,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Classic', 'Fiction'],
            ],
            [
                'title' => 'The Handmaid\'s Tale',
                'isbn' => '9780385490818',
                'description' => 'Dystopian vision of a totalitarian theocracy.',
                'publication_date' => '1985-08-17',
                'pages' => 311,
                'language' => 'English',
                'publisher' => 'Anchor Books',
                'cover_image' => 'seed/handmaids-tale.jpg',
                'rental_price_per_week' => 270,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Dystopian', 'Fiction'],
            ],
            [
                'title' => 'Brave New World',
                'isbn' => '9780307356550',
                'description' => 'A society engineered for happiness but devoid of freedom.',
                'publication_date' => '1932-08-30',
                'pages' => 288,
                'language' => 'English',
                'publisher' => 'Harper Perennial',
                'cover_image' => 'seed/brave-new-world.jpg',
                'rental_price_per_week' => 250,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Dystopian', 'Classic'],
            ],
            [
                'title' => 'Jane Eyre',
                'isbn' => '9780141441146',
                'description' => 'Gothic romance of an orphaned governess and her brooding employer.',
                'publication_date' => '1847-10-16',
                'pages' => 507,
                'language' => 'English',
                'publisher' => 'Penguin Classics',
                'cover_image' => 'seed/jane-eyre.jpg',
                'rental_price_per_week' => 240,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Classic', 'Romance'],
            ],

            // Modern English Fiction
            [
                'title' => 'The Seven Husbands of Evelyn Hugo',
                'isbn' => '9781501161933',
                'description' => 'A reclusive Hollywood icon tells her life story.',
                'publication_date' => '2017-06-13',
                'pages' => 400,
                'language' => 'English',
                'publisher' => 'Atria Books',
                'cover_image' => 'seed/evelyn-hugo.jpg',
                'rental_price_per_week' => 320,
                'total_copies' => 5,
                'available_copies' => 5,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Contemporary', 'Romance'],
            ],
            [
                'title' => 'Where the Crawdads Sing',
                'isbn' => '9780735219090',
                'description' => 'A mystery set in the marshlands of North Carolina.',
                'publication_date' => '2018-08-14',
                'pages' => 384,
                'language' => 'English',
                'publisher' => 'G.P. Putnam\'s Sons',
                'cover_image' => 'seed/crawdads-sing.jpg',
                'rental_price_per_week' => 300,
                'total_copies' => 6,
                'available_copies' => 6,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Mystery', 'Contemporary'],
            ],
            [
                'title' => 'The Thursday Murder Club',
                'isbn' => '9781984880987',
                'description' => 'Four unlikely friends meet weekly to investigate cold cases.',
                'publication_date' => '2020-09-03',
                'pages' => 336,
                'language' => 'English',
                'publisher' => 'Pamela Dorman Books',
                'cover_image' => 'seed/thursday-murder.jpg',
                'rental_price_per_week' => 280,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Mystery', 'Humor'],
            ],
            [
                'title' => 'Normal People',
                'isbn' => '9781984822178',
                'description' => 'Complex relationship between two Irish teenagers.',
                'publication_date' => '2018-08-28',
                'pages' => 288,
                'language' => 'English',
                'publisher' => 'Hogarth',
                'cover_image' => 'seed/normal-people.jpg',
                'rental_price_per_week' => 290,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Contemporary', 'Romance'],
            ],
            [
                'title' => 'The Midnight Library',
                'isbn' => '9780525559474',
                'description' => 'A library between life and death where infinite possibilities exist.',
                'publication_date' => '2020-08-13',
                'pages' => 288,
                'language' => 'English',
                'publisher' => 'Viking',
                'cover_image' => 'seed/midnight-library.jpg',
                'rental_price_per_week' => 310,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Fantasy', 'Contemporary'],
            ],

            // Fantasy & Science Fiction
            [
                'title' => 'The Hobbit',
                'isbn' => '9780547928227',
                'description' => 'Bilbo Baggins\' unexpected adventure to reclaim treasure.',
                'publication_date' => '1937-09-21',
                'pages' => 310,
                'language' => 'English',
                'publisher' => 'Houghton Mifflin Harcourt',
                'cover_image' => 'seed/hobbit.jpg',
                'rental_price_per_week' => 260,
                'total_copies' => 5,
                'available_copies' => 5,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Fantasy', 'Adventure'],
            ],
            [
                'title' => 'Dune',
                'isbn' => '9780441172719',
                'description' => 'Epic space opera on the desert planet Arrakis.',
                'publication_date' => '1965-08-01',
                'pages' => 688,
                'language' => 'English',
                'publisher' => 'Ace Books',
                'cover_image' => 'seed/dune.jpg',
                'rental_price_per_week' => 350,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Science Fiction', 'Adventure'],
            ],
            [
                'title' => 'The Name of the Wind',
                'isbn' => '9780575081383',
                'description' => 'The legend of Kvothe told by the man himself.',
                'publication_date' => '2007-03-27',
                'pages' => 722,
                'language' => 'English',
                'publisher' => 'DAW Books',
                'cover_image' => 'seed/name-wind.jpg',
                'rental_price_per_week' => 320,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Fantasy', 'Adventure'],
            ],
            [
                'title' => 'The Martian',
                'isbn' => '9780606367202',
                'description' => 'Astronaut stranded on Mars fights for survival.',
                'publication_date' => '2014-02-11',
                'pages' => 384,
                'language' => 'English',
                'publisher' => 'Broadway Books',
                'cover_image' => 'seed/martian.jpg',
                'rental_price_per_week' => 290,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Science Fiction', 'Adventure'],
            ],
            [
                'title' => 'The Hunger Games',
                'isbn' => '9780439023481',
                'description' => 'Dystopian tale of survival in a televised death match.',
                'publication_date' => '2008-09-14',
                'pages' => 374,
                'language' => 'English',
                'publisher' => 'Scholastic',
                'cover_image' => 'seed/hunger-games.jpg',
                'rental_price_per_week' => 270,
                'total_copies' => 5,
                'available_copies' => 5,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Dystopian', 'Young Adult'],
            ],
            [
                'title' => 'Mounted Painted With Turmeric',
                'isbn' => '9780231143561',
                'description' => 'Story of migration and displacement in rural Nepal.',
                'publication_date' => '1957-01-01',
                'pages' => 135,
                'language' => 'Nepali',
                'publisher' => 'Sajha Prakashan',
                'cover_image' => 'seed/basain.jpg',
                'rental_price_per_week' => 130,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Classic', 'Fiction'],
            ],
            [
                'title' => 'Himalayko Chuchuro',
                'isbn' => '9789937827789',
                'description' => 'Autobiography of Nepal\'s celebrated disabled writer.',
                'publication_date' => '2010-03-01',
                'pages' => 280,
                'language' => 'Nepali',
                'publisher' => 'Fine Print',
                'cover_image' => 'seed/himalayko-chuchuro.jpg',
                'rental_price_per_week' => 180,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Biography', 'Inspirational'],
            ],
            [
                'title' => 'Mayur Times',
                'isbn' => '9789937665321',
                'description' => 'Contemporary romance in modern Nepal.',
                'publication_date' => '2016-04-01',
                'pages' => 312,
                'language' => 'Nepali',
                'publisher' => 'Fine Print',
                'cover_image' => 'seed/mayur-times.jpg',
                'rental_price_per_week' => 170,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Romance', 'Contemporary'],
            ],
            [
                'title' => 'Damini Bhir',
                'isbn' => '9789937705080',
                'description' => 'Epic poem by Nepal\'s greatest poet.',
                'publication_date' => '1951-01-01',
                'pages' => 156,
                'language' => 'Nepali',
                'publisher' => 'Sajha Prakashan',
                'cover_image' => 'seed/damini-bhir.jpg',
                'rental_price_per_week' => 120,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Poetry', 'Classic'],
            ],
            [
                'title' => 'Jhola',
                'isbn' => '9798884793644',
                'description' => 'Powerful story about the sati system in Nepal.',
                'publication_date' => '1998-01-01',
                'pages' => 89,
                'language' => 'Nepali',
                'publisher' => 'Book Hill',
                'cover_image' => 'seed/jhola.jpg',
                'rental_price_per_week' => 110,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Social Drama', 'Fiction'],
            ],
            [
                'title' => 'Antarman',
                'isbn' => '9789937827890',
                'description' => 'Psychological exploration of human relationships.',
                'publication_date' => '2011-05-01',
                'pages' => 224,
                'language' => 'Nepali',
                'publisher' => 'Book Hill',
                'cover_image' => 'seed/antarman.jpg',
                'rental_price_per_week' => 160,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Psychology', 'Fiction'],
            ],
            [
                'title' => 'Blind Baba ko Chhoro',
                'isbn' => '9789937827456',
                'description' => 'Coming-of-age story set in rural Nepal.',
                'publication_date' => '2015-02-01',
                'pages' => 189,
                'language' => 'Nepali',
                'publisher' => 'Fine Print',
                'cover_image' => 'seed/blind-baba.jpg',
                'rental_price_per_week' => 150,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Coming of Age', 'Fiction'],
            ],

            // Hindi Literature
            [
                'title' => 'Godan',
                'isbn' => '9788172233822',
                'description' => 'Classic social novel about village life and poverty.',
                'publication_date' => '1936-01-01',
                'pages' => 336,
                'language' => 'Hindi',
                'publisher' => 'Motilal Banarsidass',
                'cover_image' => 'seed/godan.png',
                'rental_price_per_week' => 150,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Classic', 'Fiction'],
            ],
            [
                'title' => 'Kamayani',
                'isbn' => '9788120620487',
                'description' => 'Epic poem considered the greatest work in Hindi literature.',
                'publication_date' => '1936-01-01',
                'pages' => 180,
                'language' => 'Hindi',
                'publisher' => 'Motilal Banarsidass',
                'cover_image' => 'seed/kamayani.jpg',
                'rental_price_per_week' => 140,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Poetry', 'Classic'],
            ],
            [
                'title' => 'Gaban',
                'isbn' => '9788172233946',
                'description' => 'Tale of moral degradation and redemption.',
                'publication_date' => '1931-01-01',
                'pages' => 284,
                'language' => 'Hindi',
                'publisher' => 'Motilal Banarsidass',
                'cover_image' => 'seed/gaban.jpg',
                'rental_price_per_week' => 145,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Classic', 'Fiction'],
            ],
            [
                'title' => 'Nirmala',
                'isbn' => '9788172234027',
                'description' => 'Social novel about child marriage and women\'s suffering.',
                'publication_date' => '1927-01-01',
                'pages' => 224,
                'language' => 'Hindi',
                'publisher' => 'Motilal Banarsidass',
                'cover_image' => 'seed/nirmala.jpg',
                'rental_price_per_week' => 140,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Social', 'Fiction'],
            ],
            [
                'title' => 'Chandrakanta',
                'isbn' => '9788126713127',
                'description' => 'Fantasy adventure novel that popularized Hindi literature.',
                'publication_date' => '1888-01-01',
                'pages' => 456,
                'language' => 'Hindi',
                'publisher' => 'Diamond Pocket Books',
                'cover_image' => 'seed/chandrakanta.jpg',
                'rental_price_per_week' => 160,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Fantasy', 'Adventure'],
            ],
            [
                'title' => 'Rashmirathi',
                'isbn' => '9788120620494',
                'description' => 'Epic poem about Karna from Mahabharata.',
                'publication_date' => '1952-01-01',
                'pages' => 128,
                'language' => 'Hindi',
                'publisher' => 'Rajkamal Prakashan',
                'cover_image' => 'seed/rashmirathi.jpg',
                'rental_price_per_week' => 130,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Poetry', 'Mythology'],
            ],
            [
                'title' => 'Tamas',
                'isbn' => '9788126712854',
                'description' => 'Novel about partition riots and communal violence.',
                'publication_date' => '1974-01-01',
                'pages' => 420,
                'language' => 'Hindi',
                'publisher' => 'Rajkamal Prakashan',
                'cover_image' => 'seed/tamas.jpg',
                'rental_price_per_week' => 170,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Historical', 'Fiction'],
            ],

            // Japanese Literature & Manga
            [
                'title' => 'Norwegian Wood',
                'isbn' => '9780375704024',
                'description' => 'Coming-of-age story set in 1960s Tokyo.',
                'publication_date' => '1987-09-04',
                'pages' => 296,
                'language' => 'Japanese',
                'publisher' => 'Vintage International',
                'cover_image' => 'seed/norwegian-wood.jpg',
                'rental_price_per_week' => 290,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Contemporary', 'Romance'],
            ],
            [
                'title' => 'Kafka on the Shore',
                'isbn' => '9781400079278',
                'description' => 'Surreal tale of a teenage runaway and an aging simpleton.',
                'publication_date' => '2002-09-12',
                'pages' => 505,
                'language' => 'Japanese',
                'publisher' => 'Vintage',
                'cover_image' => 'seed/kafka-shore.jpg',
                'rental_price_per_week' => 320,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Magical Realism', 'Contemporary'],
            ],
            [
                'title' => 'Battle Royale',
                'isbn' => '9781421565989',
                'description' => 'Dystopian thriller about students forced to fight to the death.',
                'publication_date' => '1999-04-21',
                'pages' => 617,
                'language' => 'Japanese',
                'publisher' => 'VIZ Media',
                'cover_image' => 'seed/battle-royale.jpg',
                'rental_price_per_week' => 350,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Dystopian', 'Thriller'],
            ],
            [
                'title' => 'Snow Country',
                'isbn' => '9780679761044',
                'description' => 'Nobel Prize winner\'s lyrical tale of love and isolation.',
                'publication_date' => '1948-01-01',
                'pages' => 175,
                'language' => 'Japanese',
                'publisher' => 'Vintage',
                'cover_image' => 'seed/snow-country.jpg',
                'rental_price_per_week' => 240,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Classic', 'Romance'],
            ],

            // Popular Manga Series
            [
                'title' => 'One Piece Vol. 1',
                'isbn' => '9781421534497',
                'description' => 'Epic pirate adventure begins with Monkey D. Luffy.',
                'publication_date' => '1997-07-22',
                'pages' => 216,
                'language' => 'Japanese',
                'publisher' => 'VIZ Media',
                'cover_image' => 'seed/one-piece-1.jpg',
                'rental_price_per_week' => 180,
                'total_copies' => 5,
                'available_copies' => 5,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Manga', 'Adventure'],
            ],
            [
                'title' => 'Naruto Vol. 1',
                'isbn' => '9781591163237',
                'description' => 'Young ninja\'s journey to become Hokage.',
                'publication_date' => '1999-09-21',
                'pages' => 192,
                'language' => 'Japanese',
                'publisher' => 'VIZ Media',
                'cover_image' => 'seed/naruto-1.jpg',
                'rental_price_per_week' => 180,
                'total_copies' => 6,
                'available_copies' => 6,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Manga', 'Action'],
            ],
            [
                'title' => 'Attack on Titan Vol. 1',
                'isbn' => '9781612620244',
                'description' => 'Humanity fights for survival against giant titans.',
                'publication_date' => '2009-09-09',
                'pages' => 194,
                'language' => 'Japanese',
                'publisher' => 'Kodansha Comics',
                'cover_image' => 'seed/attack-titan-1.jpg',
                'rental_price_per_week' => 200,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Manga', 'Action'],
            ],
            [
                'title' => 'Dragon Ball Vol. 1',
                'isbn' => '9781569319208',
                'description' => 'Goku\'s quest for the seven Dragon Balls begins.',
                'publication_date' => '1984-12-03',
                'pages' => 192,
                'language' => 'Japanese',
                'publisher' => 'VIZ Media',
                'cover_image' => 'seed/dragon-ball-1.jpg',
                'rental_price_per_week' => 170,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Manga', 'Adventure'],
            ],
            [
                'title' => 'Death Note Vol. 1',
                'isbn' => '9781421501680',
                'description' => 'Light Yagami discovers a notebook that kills.',
                'publication_date' => '2003-12-01',
                'pages' => 200,
                'language' => 'Japanese',
                'publisher' => 'VIZ Media',
                'cover_image' => 'seed/death-note-1.jpg',
                'rental_price_per_week' => 190,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Manga', 'Thriller'],
            ],
            [
                'title' => 'My Hero Academia Vol. 1',
                'isbn' => '9781421582696',
                'description' => 'Izuku Midoriya dreams of becoming a hero.',
                'publication_date' => '2014-07-07',
                'pages' => 192,
                'language' => 'Japanese',
                'publisher' => 'VIZ Media',
                'cover_image' => 'seed/my-hero-1.jpg',
                'rental_price_per_week' => 190,
                'total_copies' => 5,
                'available_copies' => 5,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Manga', 'Superhero'],
            ],
            [
                'title' => 'Demon Slayer Vol. 1',
                'isbn' => '9781974700523',
                'description' => 'Tanjiro becomes a demon slayer to save his sister.',
                'publication_date' => '2016-02-15',
                'pages' => 192,
                'language' => 'Japanese',
                'publisher' => 'VIZ Media',
                'cover_image' => 'seed/demon-slayer-1.jpg',
                'rental_price_per_week' => 200,
                'total_copies' => 6,
                'available_copies' => 6,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Manga', 'Action'],
            ],
            [
                'title' => 'One Punch Man Vol. 1',
                'isbn' => '9781421585642',
                'description' => 'Saitama can defeat any enemy with a single punch.',
                'publication_date' => '2009-06-14',
                'pages' => 200,
                'language' => 'Japanese',
                'publisher' => 'VIZ Media',
                'cover_image' => 'seed/one-punch-1.jpg',
                'rental_price_per_week' => 180,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Manga', 'Comedy'],
            ],
            [
                'title' => 'Spirited Away Picture Book',
                'isbn' => '9781421505947',
                'description' => 'Studio Ghibli\'s beloved story in picture book form.',
                'publication_date' => '2001-07-20',
                'pages' => 112,
                'language' => 'Japanese',
                'publisher' => 'VIZ Media',
                'cover_image' => 'seed/spirited-away.jpg',
                'rental_price_per_week' => 220,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Children', 'Fantasy'],
            ],

            // Korean Literature & Manhwa
            [
                'title' => 'Pachinko',
                'isbn' => '9781455563937',
                'description' => 'Multi-generational saga of a Korean family in Japan.',
                'publication_date' => '2017-02-07',
                'pages' => 496,
                'language' => 'Korean',
                'publisher' => 'Grand Central Publishing',
                'cover_image' => 'seed/pachinko.jpg',
                'rental_price_per_week' => 320,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Historical', 'Family Saga'],
            ],
            [
                'title' => 'The Vegetarian',
                'isbn' => '9781101906118',
                'description' => 'Dark psychological novel about a woman\'s rebellion.',
                'publication_date' => '2007-10-30',
                'pages' => 188,
                'language' => 'Korean',
                'publisher' => 'Hogarth',
                'cover_image' => 'seed/vegetarian.jpg',
                'rental_price_per_week' => 270,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Literary Fiction', 'Psychological'],
            ],
            // [
            //     'title' => 'Tower of God Vol. 1',
            //     'isbn' => '9781975319595',
            //     'description' => 'Bam climbs the mysterious tower to find his friend.',
            //     'publication_date' => '2010-06-30',
            //     'pages' => 180,
            //     'language' => 'Korean',
            //     'publisher' => 'Yen Press',
            //     'cover_image' => 'seed/tower-god-1.jpg',
            //     'rental_price_per_week' => 190,
            //     'total_copies' => 3,
            //     'available_copies' => 3,
            //     'is_featured' => false,
            //     'status' => 'active',
            //     'genres' => ['Manhwa', 'Fantasy'],
            // ],
            [
                'title' => 'Solo Leveling Vol. 1',
                'isbn' => '9781975319434',
                'description' => 'Weak hunter becomes the world\'s strongest.',
                'publication_date' => '2016-07-25',
                'pages' => 200,
                'language' => 'Korean',
                'publisher' => 'Yen Press',
                'cover_image' => 'seed/solo-leveling-1.jpg',
                'rental_price_per_week' => 220,
                'total_copies' => 5,
                'available_copies' => 5,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Manhwa', 'Action'],
            ],
            // [
            //     'title' => 'The God of High School Vol. 1',
            //     'isbn' => '9781990778742',
            //     'description' => 'High school martial arts tournament with divine powers.',
            //     'publication_date' => '2011-04-08',
            //     'pages' => 185,
            //     'language' => 'Korean',
            //     'publisher' => 'Yen Press',
            //     'cover_image' => 'seed/god-high-school-1.jpg',
            //     'rental_price_per_week' => 190,
            //     'total_copies' => 3,
            //     'available_copies' => 3,
            //     'is_featured' => false,
            //     'status' => 'active',
            //     'genres' => ['Manhwa', 'Action'],
            // ],
            // [
            //     'title' => 'Noblesse Vol. 1',
            //     'isbn' => '9781975319839',
            //     'description' => 'Ancient noble awakens in modern world.',
            //     'publication_date' => '2007-12-30',
            //     'pages' => 200,
            //     'language' => 'Korean',
            //     'publisher' => 'Yen Press',
            //     'cover_image' => 'seed/noblesse-1.jpg',
            //     'rental_price_per_week' => 200,
            //     'total_copies' => 2,
            //     'available_copies' => 2,
            //     'is_featured' => false,
            //     'status' => 'active',
            //     'genres' => ['Manhwa', 'Supernatural'],
            // ],

            // Chinese Literature
            [
                'title' => 'The Three-Body Problem',
                'isbn' => '9780765377067',
                'description' => 'Hugo Award-winning science fiction about alien contact.',
                'publication_date' => '2006-05-01',
                'pages' => 400,
                'language' => 'Chinese',
                'publisher' => 'Tor Books',
                'cover_image' => 'seed/three-body.jpg',
                'rental_price_per_week' => 320,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Science Fiction', 'Hard SF'],
            ],
            [
                'title' => 'Red Sorghum',
                'isbn' => '9780140168549',
                'description' => 'Nobel laureate\'s tale of love and war in rural China.',
                'publication_date' => '1987-08-01',
                'pages' => 359,
                'language' => 'Chinese',
                'publisher' => 'Penguin Books',
                'cover_image' => 'seed/red-sorghum.jpg',
                'rental_price_per_week' => 280,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Historical', 'Literary Fiction'],
            ],
            [
                'title' => 'Wild Swans',
                'isbn' => '9781416543121',
                'description' => 'Three generations of Chinese women through revolution.',
                'publication_date' => '1991-09-12',
                'pages' => 524,
                'language' => 'Chinese',
                'publisher' => 'Simon & Schuster',
                'cover_image' => 'seed/wild-swans.jpg',
                'rental_price_per_week' => 300,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Biography', 'Historical'],
            ],

            // French Literature
            [
                'title' => 'The Little Prince',
                'isbn' => '9780156012195',
                'description' => 'Beloved tale of a pilot and a little prince from asteroid.',
                'publication_date' => '1943-04-06',
                'pages' => 96,
                'language' => 'French',
                'publisher' => 'Mariner Books',
                'cover_image' => 'seed/little-prince.jpg',
                'rental_price_per_week' => 180,
                'total_copies' => 5,
                'available_copies' => 5,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Children', 'Philosophy'],
            ],
            [
                'title' => 'The Stranger',
                'isbn' => '9780679720201',
                'description' => 'Existentialist novel about an emotionally detached man.',
                'publication_date' => '1942-05-19',
                'pages' => 123,
                'language' => 'French',
                'publisher' => 'Vintage',
                'cover_image' => 'seed/stranger.jpg',
                'rental_price_per_week' => 220,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Existential', 'Classic'],
            ],
            [
                'title' => 'Madame Bovary',
                'isbn' => '9780140449129',
                'description' => 'Tragic story of Emma Bovary\'s romantic delusions.',
                'publication_date' => '1857-04-30',
                'pages' => 432,
                'language' => 'French',
                'publisher' => 'Penguin Classics',
                'cover_image' => 'seed/madame-bovary.jpg',
                'rental_price_per_week' => 240,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Classic', 'Romance'],
            ],
            [
                'title' => 'The Count of Monte Cristo',
                'isbn' => '9780140449266',
                'description' => 'Epic tale of betrayal, imprisonment, and revenge.',
                'publication_date' => '1844-08-28',
                'pages' => 1276,
                'language' => 'French',
                'publisher' => 'Penguin Classics',
                'cover_image' => 'seed/monte-cristo.jpg',
                'rental_price_per_week' => 400,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Adventure', 'Classic'],
            ],

            // Spanish Literature
            [
                'title' => 'Don Quixote',
                'isbn' => '9780060188702',
                'description' => 'The adventures of the idealistic knight-errant.',
                'publication_date' => '1605-01-16',
                'pages' => 1023,
                'language' => 'Spanish',
                'publisher' => 'Harper Perennial',
                'cover_image' => 'seed/don-quixote.jpg',
                'rental_price_per_week' => 380,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Classic', 'Adventure'],
            ],
            [
                'title' => 'Love in the Time of Cholera',
                'isbn' => '9780307389732',
                'description' => 'Epic love story spanning fifty years.',
                'publication_date' => '1985-03-06',
                'pages' => 348,
                'language' => 'Spanish',
                'publisher' => 'Vintage',
                'cover_image' => 'seed/love-cholera.jpg',
                'rental_price_per_week' => 290,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Romance', 'Magical Realism'],
            ],
            [
                'title' => 'The Shadow of the Wind',
                'isbn' => '9780143034902',
                'description' => 'Gothic mystery set in post-war Barcelona.',
                'publication_date' => '2001-04-17',
                'pages' => 487,
                'language' => 'Spanish',
                'publisher' => 'Penguin Books',
                'cover_image' => 'seed/shadow-wind.jpg',
                'rental_price_per_week' => 310,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Mystery', 'Gothic'],
            ],

            // Russian Literature
            [
                'title' => 'Crime and Punishment',
                'isbn' => '9780486415871',
                'description' => 'Psychological exploration of guilt and redemption.',
                'publication_date' => '1866-01-01',
                'pages' => 671,
                'language' => 'Russian',
                'publisher' => 'Dover Publications',
                'cover_image' => 'seed/crime-punishment.jpg',
                'rental_price_per_week' => 320,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Classic', 'Philosophical'],
            ],
            [
                'title' => 'War and Peace',
                'isbn' => '9781400079988',
                'description' => 'Epic novel of Russian aristocracy during Napoleonic era.',
                'publication_date' => '1869-01-01',
                'pages' => 1225,
                'language' => 'Russian',
                'publisher' => 'Vintage',
                'cover_image' => 'seed/war-peace.jpg',
                'rental_price_per_week' => 450,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Classic', 'Historical'],
            ],
            [
                'title' => 'Anna Karenina',
                'isbn' => '9780143035008',
                'description' => 'Tragic love story of aristocratic Russian society.',
                'publication_date' => '1877-01-01',
                'pages' => 838,
                'language' => 'Russian',
                'publisher' => 'Penguin Classics',
                'cover_image' => 'seed/anna-karenina.jpg',
                'rental_price_per_week' => 380,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Classic', 'Romance'],
            ],
            [
                'title' => 'The Brothers Karamazov',
                'isbn' => '9780374528379',
                'description' => 'Philosophical novel about faith, doubt, and morality.',
                'publication_date' => '1880-01-01',
                'pages' => 796,
                'language' => 'Russian',
                'publisher' => 'Farrar, Straus and Giroux',
                'cover_image' => 'seed/brothers-karamazov.jpg',
                'rental_price_per_week' => 360,
                'total_copies' => 2,
                'available_copies' => 2,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Classic', 'Philosophical'],
            ],

            // Self-Help & Productivity
            [
                'title' => 'Atomic Habits',
                'isbn' => '9780735211292',
                'description' => 'A proven framework for building good habits and breaking bad ones.',
                'publication_date' => '2018-10-16',
                'pages' => 320,
                'language' => 'English',
                'publisher' => 'Avery',
                'cover_image' => 'seed/atomic-habits.webp',
                'rental_price_per_week' => 200,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Self-help', 'Productivity'],
            ],
            [
                'title' => 'The 7 Habits of Highly Effective People',
                'isbn' => '9781451639612',
                'description' => 'Powerful lessons in personal change and effectiveness.',
                'publication_date' => '1989-08-15',
                'pages' => 381,
                'language' => 'English',
                'publisher' => 'Free Press',
                'cover_image' => 'seed/7-habits.jpg',
                'rental_price_per_week' => 220,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Self-help', 'Leadership'],
            ],
            [
                'title' => 'Deep Work',
                'isbn' => '9781455586691',
                'description' => 'Rules for focused success in a distracted world.',
                'publication_date' => '2016-01-05',
                'pages' => 296,
                'language' => 'English',
                'publisher' => 'Grand Central Publishing',
                'cover_image' => 'seed/deep-work.jpg',
                'rental_price_per_week' => 240,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Productivity', 'Self-help'],
            ],
            [
                'title' => 'How to Win Friends and Influence People',
                'isbn' => '9780671027032',
                'description' => 'Timeless advice on building relationships and leadership.',
                'publication_date' => '1936-10-12',
                'pages' => 291,
                'language' => 'English',
                'publisher' => 'Simon & Schuster',
                'cover_image' => 'seed/win-friends.jpg',
                'rental_price_per_week' => 190,
                'total_copies' => 5,
                'available_copies' => 5,
                'is_featured' => true,
                'status' => 'active',
                'genres' => ['Self-help', 'Communication'],
            ],
            [
                'title' => 'The Power of Now',
                'isbn' => '9781577314806',
                'description' => 'A guide to spiritual enlightenment through present moment awareness.',
                'publication_date' => '1997-08-19',
                'pages' => 236,
                'language' => 'English',
                'publisher' => 'New World Library',
                'cover_image' => 'seed/power-now.jpg',
                'rental_price_per_week' => 210,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Spirituality', 'Self-help'],
            ],
            [
                'title' => 'Mindset',
                'isbn' => '9780345472328',
                'description' => 'The new psychology of success through growth mindset.',
                'publication_date' => '2006-02-28',
                'pages' => 276,
                'language' => 'English',
                'publisher' => 'Random House',
                'cover_image' => 'seed/mindset.jpg',
                'rental_price_per_week' => 200,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Psychology', 'Self-help'],
            ],

            // Business & Finance
            [
                'title' => 'Rich Dad Poor Dad',
                'isbn' => '9781612680194',
                'description' => 'Personal finance classic that contrasts two financial mindsets.',
                'publication_date' => '1997-04-01',
                'pages' => 336,
                'language' => 'English',
                'publisher' => 'Plata Publishing',
                'cover_image' => 'seed/rich-dad.jpg',
                'rental_price_per_week' => 160,
                'total_copies' => 4,
                'available_copies' => 4,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Finance', 'Self-help'],
            ],
            [
                'title' => 'The Intelligent Investor',
                'isbn' => '9780060555665',
                'description' => 'The definitive book on value investing.',
                'publication_date' => '1949-03-01',
                'pages' => 623,
                'language' => 'English',
                'publisher' => 'Harper Business',
                'cover_image' => 'seed/intelligent-investor.jpg',
                'rental_price_per_week' => 280,
                'total_copies' => 3,
                'available_copies' => 3,
                'is_featured' => false,
                'status' => 'active',
                'genres' => ['Finance', 'Investment'],
            ],
        ];

        shuffle($books);
        shuffle($books);
        shuffle($books);

        foreach ($books as $bookItem) {
            $genreNames = $bookItem['genres'];
            unset($bookItem['genres']);
            // $bookData = $this->fetchBookFromGoogle($bookItem['title']);
            if (Book::where('isbn', $bookItem['isbn'])->exists()) {
                continue;
            }
            $bookData = $this->fetchBookFromGoogle($bookItem['isbn']);
            if ($bookData) {
                $timestamp = Carbon::now()->subDays(rand(1, 365));
                $copies = random_int(1, 8);
                $filename = Str::slug($bookData['title']) . '.jpg';
                $bookData['cover_image'] = $this->downloadCoverImage($filename, $bookItem['isbn']);
                $bookData['rental_price_per_week'] = $bookItem['rental_price_per_week']; // or some logic
                $bookData['total_copies'] = $copies;
                $bookData['available_copies'] = $copies;
                $bookData['language'] = $bookItem['language'];
                $bookData['is_featured'] = array_rand([true, false], 1);
                $bookData['status'] = 'active';
                try {
                    $book = Book::updateOrCreate(['isbn' => $bookItem['isbn']], [
                        ...$bookData,
                        'created_at' => $timestamp,
                        'updated_at' => $timestamp
                    ]);
                    FacadesLog::info("Book created with dynamic time for {$bookItem['title']} with ISBN {$bookItem['isbn']}");
                } catch (\Exception $e) {
                    FacadesLog::info("Book not created with dynamic time for {$bookItem['title']} with ISBN {$bookItem['isbn']}");
                    // $book = Book::updateOrCreate(['isbn' => $bookItem['isbn']], [
                    //     ...$bookData
                    // ]);
                }
                $genreIds = \App\Models\Genre::whereIn('name', $genreNames)->pluck('id');
                $book->genres()->sync($genreIds);
            } else {
                FacadesLog::info("Book not found for {$bookItem['title']} with ISBN {$bookItem['isbn']}");
            }
        }
    }

    public function downloadCoverImage($filename, $isbn = null, $url = null)
    {
        $path = "seed/{$filename}";

        // if (false) return "seed/{$filename}";

        if (Storage::disk('public')->exists($path)) {
            FacadesLog::info("Image already exists for $filename");
            return "storage/{$path}";
        }

        if ($isbn) {
            $url = "https://covers.openlibrary.org/b/isbn/{$isbn}.jpg?default=false";
        } else {
            if (!$url) {
                FacadesLog::info("Image not found for $filename, Add it manually");
                return "storage/{$path}";
            }
        }

        try {
            $image = file_get_contents($url);
        } catch (\Exception $e) {
            FacadesLog::info("Image not found for $filename");
            return null;
        }
        Storage::disk('public')->put($path, $image);
        FacadesLog::info("Image downloaded for $filename");

        return "storage/{$path}";
    }

    private function fetchBookFromGoogle($isbn)
    {
        $response = Http::get("https://www.googleapis.com/books/v1/volumes", [
            'q' => "isbn:$isbn"
        ]);

        $book = $response->json()['items'][0]['volumeInfo'] ?? null;

        if (!$book) return null;

        return [
            'title' => $book['title'] ?? null,
            'author' => implode(', ', $book['authors'] ?? []),
            'isbn' => $isbn,
            'description' => $book['description'] ?? '',
            'publication_date' => $book['publishedDate'] ?? null,
            'pages' => ($book['pageCount'] ?? null) || random_int(100, 1000),
            'language' => $book['language'] ?? null,
            'publisher' => $book['publisher'] ?? null,
            'cover_image' => $book['imageLinks']['thumbnail'] ?? null,
            // 'genres' => $book['categories'] ?? [],
        ];
    }
}
